### PR TITLE
Creating RandomForest Baseline model

### PR DESCRIPTION
**Pull request by tm-abby-moreno**
## What does this PR do?

1. Studies sample LGU data for Zamboanga dengue cases and checks if the threshold definition of 75th percentile holds. After checking the data, it is then labeled each week of it is an outbreak or not. 
2. Links the socioeconomic variables and the climate variables to the sample dengue data. 
    - Climate variables are aggregated weekly and matched by barangay + start of week date
    - Most datasets such as OSM, Ookla, Nightlights, WorldPop were joined using the year since they were annual datasets
    - The rest of the datasets were considered static and was joined using only the barangay codes.
    - Output of this table is the dataset we will be using in the baseline model.
3. Experiments for RandomForest Classifier were conducted. Partial results were given in the slack thread. 

## Where should the reviewers start?

In the `notebooks/baseline-model/` directory. 

## Other notes

Created this PR to track feedback and discussions for the baseline model. Current run is not yet final, will still need to do a few more revisions.

### CODE REVIEW

**Comment by tm-jace-peralta** [comment]
Hi @tm-abby-moreno, thanks for the edits! As aligned over call, to close this PR and this sprint task, we need to:
1. Recreate the notebooks to take in city-weekly data
2. Correct the function that computes for outbreak length
3. Fill missing timestamps in input dataframe, keep features when filling for dates without cases
4. Add model tuning (GridSearch) and more metrics (classification report) in model selection notebook
5. Move all notebooks to folder `baseline_model/prototype/`

For the final submission, we need to create a single end-to-end Colab notebook from the current 5 notebooks, which reads directly from a copy of the linked dataset uploaded in a Google Drive.

**Comment by tm-abby-moreno** [comment]
Hi @tm-jace-peralta, took some time to update the notebooks from the last review. Did the following in this update: 
- cleaning the former notebooks and updating the former code and aggregation to make use of the central data instead of the LGU data
- Did no additional edits on the timestamps issue we had before
  - central data's date is already weekly
  - dates are also already complete --- did not need the additional step from the previous notebook of adding missing timestamps
- Moved the previous notebooks into a subdirectory under `baseline_model/prototype`
- Created a main single baseline-model notebook that covers the steps from filtering and selecting features, splitting training and testing data, running RF classifier model, and visualization.
  - Flagging here that the notebook assumes that the linked dataset is downloaded. Did not include here the prototype notebooks for labelling the cases if outbreak or not. --- Will discuss this with Daf if that step is already in the linking datasets notebook she created. 
 

 ### Where should reviewers start?

Would be easier for you to just check the `baseline-model/baseline-model-demo.ipynb` notebook since it covers the former notebooks. Your comments there I'll just apply to the prototype notebooks. 

Just wanted to flag that for the plots I am thinking of removing the last plot (dumbbell plot for actual period of outbreak and gradient in the background for the predicted probabilities; **first screenshot**) and replacing it with the plot above this (plot of actual cases and predicted probabilities for the background; **second screenshot**).

image
image

**Comment by tm-jace-peralta** [comment]
Hi @tm-abby-moreno thanks for the revisions! I pushed changes to improve flow and code readability.
Further comments:
1. There are still code cells that preps the read linked dataset file for the model. For the model, we can assume that the user will run the linking notebook to generate the data and only has to read the resulting file from the GDrive/local folder. Thus we should remove the cells that:
- Fill nightlight columns with 0s
- Remove unused columns 
and assume that this is all done by the time a user runs the model.
2. However, lets keep the steps that engineers features from the linked dataset  that are intended for this specific model:
- Keep cell for lagged cases columns
- Add cell/s to generate outbreak label column (you may use your function from the prototype notebooks)
3. Please add short markdown text explaining key insights from the viz in the notebook

On the questions:
1. Yes, upon looking at it, we can remove the brgy-weekly notebooks. (I still made a few markdown edits in those files, but kindly disregard)
2. I agree that we can drop the dumbbell plot and replace with the line with background shading plot. Thanks for coming up with this new viz, it looks better than our original design.

**Comment by tm-abby-moreno** [comment]
Hi Jace, updated the demo notebook. I saw the updates you made on the branch for the markdowns, highly appreciate this!! **Changes made**:

- Added more explainer markdowns on certain steps 
- Added short insights on certain visualizations regarding the model 
- Removed the brgy-weekly notebooks (I kept a local copy of them just in case)
- Add the outbreak tagging/labeling code into the notebook (not yet tested again though) 

Still pending to do from me is to update the linked dataset to be from the linking notebook (daf was still debugging but I think tomorrow should be able to add this in). For now I only marked which of the preprocessing steps I will remove once I add the clean dataset already.

**Review by tm-jace-peralta — APPROVED** [review]
All good, can now merge! :D

**Pull request merged**
